# Site
repository: no1kazami.github.io
#favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 최경희
title: 게임 클라이언트 프로그래머
email: usinggo@gmail.com
GitHub: https://github.com/no1kazami/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  no1kazami
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  C/C++, Unreal Engine 기반의 게임 클라이언트 개발자 최경희입니다.<br/>
  리니지, 블레이드, 팡야, 기간틱엑스, 미소스등 여러 회사에서 여러 프로젝트 경험을 쌓았습니다.<br/>
  가능하면 프로젝트의 핵심 기능 구현에 참여하려고 노력해왔고 회사 업무와는 별개로 지금까지 **게임 1종, 앱 3종**등 개인 프로젝트를 꾸준히 진행하고 있습니다.<br/>
  현재는 엔씨소프트에서 글로벌 IP와 협업한 MMORPG를 개발 중입니다.<br/>

content:
 - title: 경력 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 엔씨소프트
        link: ncsoft.com
        # link_text: boringcompany.com
        sub_title: 게임 클라이언트 프로그래머
        caption: 2019.04 ~ 재직 중
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            * 카메라 시스템
            * 전투, 타겟 시스템
            * UI & 컨텐츠 작업

  - title: 프로젝트 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Skyline(엔씨소프트)
        link:
        quote: >
          2021.07 ~ 현재
        description: | # this will include new lines to allow paragraphs
            게임에 중요한 카메라 관련 시스템을 개발 하고 있습니다. 또한 각종 전투, 타겟 시스템등 관련 작업을 진행하고 있습니다.
           * 카메라 통합 시스템 구현 : 파편화된 카메라 기능들을 통합하고 관리할 수 있는 데이터 구조를 제공하여 관련 작업의 능률을 올렸습니다.
           * 카메라의 여러가지 개별 기능 구현(동적 카메라, 카메라 정렬등)
           * 특정 개체 및 파츠를 타겟팅 할 수 있는 타겟 시스템 구현
           * 슬링 인디케이터의 예상 궤적 서버 동기화 및 시각화 구현
           * 각 시스템에 필요한 UI 구현
    
      - layout: top-middle
        title: 리니지 리마스터(엔씨소프트)
        link:
        quote: >
          2019.04 ~ 2021.06
        description: | # this will include new lines to allow paragraphs
          * 보이스 채팅 : CEF(Chromium Embedded Framework)를 사용하여 구현
          * 스트리밍 서비스 : 게임 클라이언트와 스트리밍 클라이언트의 상태 동기화 구현
          * 컨텐츠 & UI 추가 및 개선 작업
          * 해외 서비스 지원 작업         

  - title: 기술 스택
    layout: text
    content: | # this will include new lines to allow paragraphs
      - C/C++
      - Python
      - Unreal Engine

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
