# Site
repository: no1kazami.github.io
#favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 최경희
title: 게임 클라이언트 프로그래머
email: usinggo@gmail.com
GitHub: https://github.com/no1kazami/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  no1kazami
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  새로운 도전을 좋아하는 게임 클라이언트 개발자 최경희입니다.<br/>
  여러 회사에서 신규 개발 뿐만 아니라 여러 라이브 프로젝트 경험을 쌓았습니다.<br/>
  가능하면 프로젝트의 핵심 기능 구현에 참여하려고 노력해왔고 많은 경험을 쌓았습니다.<br/> 
  또한 자기개발을 위해 회사 업무와는 별개로 게임, 어플 등 개인 프로젝트를 꾸준히 진행하고 있습니다.<br/>
  현재는 엔씨소프트에서 글로벌 IP와 협업한 MMORPG를 개발 중입니다.<br/>

content:
  - title: 기술 스택
    layout: text
    content: | # this will include new lines to allow paragraphs
      - C/C++
      - Python
      - Firebase
      - Unreal Engine
      
  - title: 경력 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 엔씨소프트
        link: https://www.ncsoft.com
        sub_title: 게임 클라이언트 프로그래머
        caption: 2019.04 ~ 재직 중
        quote: >
          <mark>리니지 리마스터, Skyline</mark> 
        description: | # this will include new lines to allow paragraphs
            * 카메라 시스템
            * 전투, 타겟 시스템
            * UI & 컨텐츠
            * 라이브 서비스
      - layout: left
        title: 액션스퀘어
        link: https://www.action2quare.com
        sub_title: 게임 클라이언트 프로그래머
        caption: 2015.02 ~ 2019.03
        quote: >
          <mark>블레이드, 기간틱엑스</mark> 
        description: | # this will include new lines to allow paragraphs
            * 배경 최적화
            * 퍼포먼스 향상
            * 전투 시스템
            * UI & 컨텐츠
            * 라이브 서비스
      - layout: left
        title: 엔트리브 소프트
        sub_title: 게임 클라이언트 프로그래머
        caption: 2013.07 ~ 2015.02
        quote: >
          <mark>팡야</mark> 
        description: | # this will include new lines to allow paragraphs
            * Shader
            * UI & 컨텐츠
            * 라이브 서비스
      - layout: left
        title: T3 엔터테인먼트
        link: https://www.t3.co.kr
        sub_title: 게임 클라이언트 프로그래머
        caption: 2010.09 ~ 2013.07
        quote: >
          <mark>미소스, Project S</mark> 
        description: | # this will include new lines to allow paragraphs
            * 전투 시스템
            * UI & 컨텐츠
            * 라이브 서비스

  - title: 프로젝트 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Skyline(엔씨소프트)
        link:
        quote: >
          2021.07 ~ 현재
        description: | # this will include new lines to allow paragraphs
            UnrealEngine5로 개발중인 글로벌 IP MMORPG로 초기 개발 단계부터 참여하였습니다.<br/>
            게임에 중요한 카메라 관련 시스템을 개발 하고 있습니다.<br/>
            또한 각종 전투, 타겟 시스템 등 관련 작업을 진행하고 있습니다.
            * 카메라 통합 시스템 구현 : 파편화된 카메라 기능들을 통합하고 관리할 수 있는 데이터 구조를 제공하여 관련 작업의 능률을 올렸습니다.
            * 카메라의 여러가지 개별 기능 구현(동적 카메라, 카메라 정렬 등)
            * 특정 개체 및 파츠를 타겟팅 할 수 있는 타겟 시스템 구현
            * 슬링 인디케이터의 예상 궤적 서버 동기화 및 시각화 구현
            * 조준 시스템 : 조준 오차각 및 패널티 동기화 작업 등 조준에 필요한 기능 구현  
            * 각 시스템에 필요한 UI 구현
    
      - layout: top-middle
        title: 리니지 리마스터(엔씨소프트)
        link:
        quote: >
          2019.04 ~ 2021.06
        description: | # this will include new lines to allow paragraphs
            클라이언트 개발 및 출시 이후 라이브 서비스 유지 작업을 진행하였습니다.
            * 보이스 채팅 : CEF(Chromium Embedded Framework)를 사용하여 구현
            * 스트리밍 서비스 : 게임 클라이언트와 스트리밍 클라이언트의 상태 동기화 구현
            * 컨텐츠 & UI 추가 및 개선 작업
            * 해외 서비스 지원 작업
            
      - layout: top-middle
        title: 기간틱엑스(액션스퀘어)
        link:
        quote: >
          2017.02 ~ 2019.03
        description: | # this will include new lines to allow paragraphs
            UnrealEngine4로 개발한 TPS 게임으로 초기 개발 단계부터 참여하였습니다.
            * 아이템, 인벤토리 등 기반 시스템 구현
            * 배경 최적화 작업 지원
            * 컨텐츠 & UI 추가 및 개선 작업
            
      - layout: top-middle
        title: 블레이드(액션스퀘어)
        link:
        quote: >
          2015.02 ~ 2017.02
        description: | # this will include new lines to allow paragraphs
            UnrealEngine3로 개발한 모바일 액션 RPG 게임으로 클라이언트 개발 및 출시 이후 라이브 서비스 유지 작업을 진행하였습니다.
            * 프로파일링을 통해 프레임이 떨어지는 부분을 개선하여 클라이언트 퍼포먼스 향상
            * 스킬, 버프 등 전반적인 전투 시스템 구현
            * 컨텐츠 & UI 추가 및 개선 작업
            
      - layout: top-middle
        title: 팡야(엔트리브 소프트)
        link:
        quote: >
          2013.07 ~ 2015.02
        description: | # this will include new lines to allow paragraphs
            PC 골프 게임으로 클라이언트 개발 및 출시 이후 라이브 서비스 유지 작업을 진행하였습니다.
            * shader : Fake HDR, RimLight, DOF, Fxaa 등을 구현하여 10년된 게임의 그래픽 퀄리티를 업그레이드
            * 컨텐츠 & UI 추가 및 개선 작업
            * 해외 서비스 지원 작업
            
      - layout: top-middle
        title: Project S(T3 엔터테인먼트)
        link:
        quote: >
          2011.09 ~ 2013.07
        description: | # this will include new lines to allow paragraphs
            AOS장르의 게임으로 초기 개발 단계부터 참여하였습니다.
            * 스킬, 자동공격, 추적 등 전반적인 전투 시스템 구현
            * 컨텐츠 & UI 추가 및 개선 작업
            
      - layout: top-middle
        title: 미소스(T3 엔터테인먼트)
        link:
        quote: >
          2010.09 ~ 2011.09
        description: | # this will include new lines to allow paragraphs
            MORPG 게임으로 클라이언트 개발 및 출시 이후 라이브 서비스 유지 작업을 진행하였습니다.
            * 제작, 길드 등 주요 시스템 구현 및 기능 개선
            * 컨텐츠 & UI 추가 및 개선 작업
            * 해외 서비스 지원 작업

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
